// flow-typed signature: ab6a176c622ed61a9b3b5e2ea981e426
// flow-typed version: <<STUB>>/react-router-flow-types_v^1.0.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-flow-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-flow-types' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'react-router-flow-types/index' {
    declare module.exports: $Exports<'react-router-flow-types'>;
}
declare module 'react-router-flow-types/index.js' {
    declare module.exports: $Exports<'react-router-flow-types'>;
}
