// flow-typed signature: a7d1735c8929b06c1e063eda19d46171
// flow-typed version: <<STUB>>/speed-measure-webpack-plugin_v^1.3.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'speed-measure-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'speed-measure-webpack-plugin' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'speed-measure-webpack-plugin/colours' {
    declare module.exports: any;
}

declare module 'speed-measure-webpack-plugin/jest.config' {
    declare module.exports: any;
}

declare module 'speed-measure-webpack-plugin/loader' {
    declare module.exports: any;
}

declare module 'speed-measure-webpack-plugin/neutrino' {
    declare module.exports: any;
}

declare module 'speed-measure-webpack-plugin/output' {
    declare module.exports: any;
}

declare module 'speed-measure-webpack-plugin/utils' {
    declare module.exports: any;
}

declare module 'speed-measure-webpack-plugin/utils.test' {
    declare module.exports: any;
}

declare module 'speed-measure-webpack-plugin/WrappedPlugin/index' {
    declare module.exports: any;
}

// Filename aliases
declare module 'speed-measure-webpack-plugin/colours.js' {
    declare module.exports: $Exports<'speed-measure-webpack-plugin/colours'>;
}
declare module 'speed-measure-webpack-plugin/index' {
    declare module.exports: $Exports<'speed-measure-webpack-plugin'>;
}
declare module 'speed-measure-webpack-plugin/index.js' {
    declare module.exports: $Exports<'speed-measure-webpack-plugin'>;
}
declare module 'speed-measure-webpack-plugin/jest.config.js' {
    declare module.exports: $Exports<'speed-measure-webpack-plugin/jest.config'>;
}
declare module 'speed-measure-webpack-plugin/loader.js' {
    declare module.exports: $Exports<'speed-measure-webpack-plugin/loader'>;
}
declare module 'speed-measure-webpack-plugin/neutrino.js' {
    declare module.exports: $Exports<'speed-measure-webpack-plugin/neutrino'>;
}
declare module 'speed-measure-webpack-plugin/output.js' {
    declare module.exports: $Exports<'speed-measure-webpack-plugin/output'>;
}
declare module 'speed-measure-webpack-plugin/utils.js' {
    declare module.exports: $Exports<'speed-measure-webpack-plugin/utils'>;
}
declare module 'speed-measure-webpack-plugin/utils.test.js' {
    declare module.exports: $Exports<'speed-measure-webpack-plugin/utils.test'>;
}
declare module 'speed-measure-webpack-plugin/WrappedPlugin/index.js' {
    declare module.exports: $Exports<'speed-measure-webpack-plugin/WrappedPlugin/index'>;
}
