export const EXAMPLE_MODULE_NAME = 'example';
export const EXAMPLE_ACTION_TYPE = {
    GET_EXAMPLE_FAIL: 'EXAMPLE__GET_EXAMPLE_FAIL',
    GET_EXAMPLE_START: 'EXAMPLE__GET_EXAMPLE_START',
    GET_EXAMPLE_SUCCESS: 'EXAMPLE__GET_EXAMPLE_SUCCESS',
};
