// flow-typed signature: c43f94c04e9226cde5118c42298162e6
// flow-typed version: <<STUB>>/@userstory/babel-preset_v^0.7.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@userstory/babel-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@userstory/babel-preset' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@userstory/babel-preset/src/index' {
    declare module.exports: any;
}

// Filename aliases
declare module '@userstory/babel-preset/src/index.js' {
    declare module.exports: $Exports<'@userstory/babel-preset/src/index'>;
}
