// flow-typed signature: 95c4f5c1f1f7f8a0d8d52b22a1a5b84c
// flow-typed version: <<STUB>>/@userstory/eslint-config_vgit+ssh://git@gitlab.userstory.ru:userstory-dev/eslint-config.git/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@userstory/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@userstory/eslint-config' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@userstory/eslint-config/standards/manual/es5/manual' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/manual/es6/manual' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/manual/jsx/manual' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/es5/flow' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/es5/post' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/es5/userstory-acma' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/es5/userstory-call-center' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/es5/userstory-csg' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/es5/userstory-frontend' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/es5/userstory-kips' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/es5/userstory-touch-tv' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/es5/userstory-u29n' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/es6/post' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/es6/userstory-kips' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/jsx/flow' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/jsx/post' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/jsx/userstory-acma' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/jsx/userstory-call-center' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/jsx/userstory-csg' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/jsx/userstory-frontend' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/jsx/userstory-kips' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/jsx/userstory-touch-tv' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/post/jsx/userstory-u29n' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es5/flow' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es5/pre' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es5/userstory-acma' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es5/userstory-call-center' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es5/userstory-csg' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es5/userstory-frontend' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es5/userstory-kips-scenario' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es5/userstory-kips' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es5/userstory-telebreeze-cloud' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es5/userstory-tooth-bank' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es5/userstory-touch-tv' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es5/userstory-u29n' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es6/pre' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es6/userstory-kips-scenario' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es6/userstory-kips' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es6/userstory-telebreeze-cloud' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/es6/userstory-tooth-bank' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/jsx/flow' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/jsx/pre' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/jsx/userstory-acma' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/jsx/userstory-call-center' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/jsx/userstory-csg' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/jsx/userstory-frontend' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/jsx/userstory-kips' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/jsx/userstory-telebreeze-cloud' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/jsx/userstory-tooth-bank' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/jsx/userstory-touch-tv' {
    declare module.exports: any;
}

declare module '@userstory/eslint-config/standards/pre/jsx/userstory-u29n' {
    declare module.exports: any;
}

// Filename aliases
declare module '@userstory/eslint-config/standards/manual/es5/manual.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/manual/es5/manual'>;
}
declare module '@userstory/eslint-config/standards/manual/es6/manual.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/manual/es6/manual'>;
}
declare module '@userstory/eslint-config/standards/manual/jsx/manual.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/manual/jsx/manual'>;
}
declare module '@userstory/eslint-config/standards/post.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post'>;
}
declare module '@userstory/eslint-config/standards/post/es5/flow.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/es5/flow'>;
}
declare module '@userstory/eslint-config/standards/post/es5/post.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/es5/post'>;
}
declare module '@userstory/eslint-config/standards/post/es5/userstory-acma.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/es5/userstory-acma'>;
}
declare module '@userstory/eslint-config/standards/post/es5/userstory-call-center.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/es5/userstory-call-center'>;
}
declare module '@userstory/eslint-config/standards/post/es5/userstory-csg.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/es5/userstory-csg'>;
}
declare module '@userstory/eslint-config/standards/post/es5/userstory-frontend.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/es5/userstory-frontend'>;
}
declare module '@userstory/eslint-config/standards/post/es5/userstory-kips.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/es5/userstory-kips'>;
}
declare module '@userstory/eslint-config/standards/post/es5/userstory-touch-tv.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/es5/userstory-touch-tv'>;
}
declare module '@userstory/eslint-config/standards/post/es5/userstory-u29n.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/es5/userstory-u29n'>;
}
declare module '@userstory/eslint-config/standards/post/es6/post.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/es6/post'>;
}
declare module '@userstory/eslint-config/standards/post/es6/userstory-kips.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/es6/userstory-kips'>;
}
declare module '@userstory/eslint-config/standards/post/jsx/flow.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/jsx/flow'>;
}
declare module '@userstory/eslint-config/standards/post/jsx/post.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/jsx/post'>;
}
declare module '@userstory/eslint-config/standards/post/jsx/userstory-acma.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/jsx/userstory-acma'>;
}
declare module '@userstory/eslint-config/standards/post/jsx/userstory-call-center.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/jsx/userstory-call-center'>;
}
declare module '@userstory/eslint-config/standards/post/jsx/userstory-csg.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/jsx/userstory-csg'>;
}
declare module '@userstory/eslint-config/standards/post/jsx/userstory-frontend.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/jsx/userstory-frontend'>;
}
declare module '@userstory/eslint-config/standards/post/jsx/userstory-kips.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/jsx/userstory-kips'>;
}
declare module '@userstory/eslint-config/standards/post/jsx/userstory-touch-tv.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/jsx/userstory-touch-tv'>;
}
declare module '@userstory/eslint-config/standards/post/jsx/userstory-u29n.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/post/jsx/userstory-u29n'>;
}
declare module '@userstory/eslint-config/standards/pre.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre'>;
}
declare module '@userstory/eslint-config/standards/pre/es5/flow.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es5/flow'>;
}
declare module '@userstory/eslint-config/standards/pre/es5/pre.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es5/pre'>;
}
declare module '@userstory/eslint-config/standards/pre/es5/userstory-acma.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es5/userstory-acma'>;
}
declare module '@userstory/eslint-config/standards/pre/es5/userstory-call-center.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es5/userstory-call-center'>;
}
declare module '@userstory/eslint-config/standards/pre/es5/userstory-csg.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es5/userstory-csg'>;
}
declare module '@userstory/eslint-config/standards/pre/es5/userstory-frontend.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es5/userstory-frontend'>;
}
declare module '@userstory/eslint-config/standards/pre/es5/userstory-kips-scenario.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es5/userstory-kips-scenario'>;
}
declare module '@userstory/eslint-config/standards/pre/es5/userstory-kips.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es5/userstory-kips'>;
}
declare module '@userstory/eslint-config/standards/pre/es5/userstory-telebreeze-cloud.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es5/userstory-telebreeze-cloud'>;
}
declare module '@userstory/eslint-config/standards/pre/es5/userstory-tooth-bank.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es5/userstory-tooth-bank'>;
}
declare module '@userstory/eslint-config/standards/pre/es5/userstory-touch-tv.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es5/userstory-touch-tv'>;
}
declare module '@userstory/eslint-config/standards/pre/es5/userstory-u29n.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es5/userstory-u29n'>;
}
declare module '@userstory/eslint-config/standards/pre/es6/pre.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es6/pre'>;
}
declare module '@userstory/eslint-config/standards/pre/es6/userstory-kips-scenario.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es6/userstory-kips-scenario'>;
}
declare module '@userstory/eslint-config/standards/pre/es6/userstory-kips.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es6/userstory-kips'>;
}
declare module '@userstory/eslint-config/standards/pre/es6/userstory-telebreeze-cloud.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es6/userstory-telebreeze-cloud'>;
}
declare module '@userstory/eslint-config/standards/pre/es6/userstory-tooth-bank.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/es6/userstory-tooth-bank'>;
}
declare module '@userstory/eslint-config/standards/pre/jsx/flow.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/jsx/flow'>;
}
declare module '@userstory/eslint-config/standards/pre/jsx/pre.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/jsx/pre'>;
}
declare module '@userstory/eslint-config/standards/pre/jsx/userstory-acma.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/jsx/userstory-acma'>;
}
declare module '@userstory/eslint-config/standards/pre/jsx/userstory-call-center.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/jsx/userstory-call-center'>;
}
declare module '@userstory/eslint-config/standards/pre/jsx/userstory-csg.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/jsx/userstory-csg'>;
}
declare module '@userstory/eslint-config/standards/pre/jsx/userstory-frontend.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/jsx/userstory-frontend'>;
}
declare module '@userstory/eslint-config/standards/pre/jsx/userstory-kips.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/jsx/userstory-kips'>;
}
declare module '@userstory/eslint-config/standards/pre/jsx/userstory-telebreeze-cloud.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/jsx/userstory-telebreeze-cloud'>;
}
declare module '@userstory/eslint-config/standards/pre/jsx/userstory-tooth-bank.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/jsx/userstory-tooth-bank'>;
}
declare module '@userstory/eslint-config/standards/pre/jsx/userstory-touch-tv.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/jsx/userstory-touch-tv'>;
}
declare module '@userstory/eslint-config/standards/pre/jsx/userstory-u29n.js' {
    declare module.exports: $Exports<'@userstory/eslint-config/standards/pre/jsx/userstory-u29n'>;
}
