// flow-typed signature: 5ac9f708a7acd1804d3eeb5922a1e04a
// flow-typed version: <<STUB>>/@userstory/stylelint-config_vgit+ssh://git@gitlab.userstory.ru:userstory-dev/stylelint-config.git/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@userstory/stylelint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@userstory/stylelint-config' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@userstory/stylelint-config/standards/css/manual' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/css/post' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/css/pre' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/css/userstory-cp' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/css/userstory-csg' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/css/userstory-kips' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/css/userstory-touch-tv' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/less/manual' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/less/post' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/less/pre' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/less/userstory-cp' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/less/userstory-csg' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/less/userstory-kips' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/less/userstory-touch-tv' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/post' {
    declare module.exports: any;
}

declare module '@userstory/stylelint-config/standards/pre' {
    declare module.exports: any;
}

// Filename aliases
declare module '@userstory/stylelint-config/standards/css/manual.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/css/manual'>;
}
declare module '@userstory/stylelint-config/standards/css/post.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/css/post'>;
}
declare module '@userstory/stylelint-config/standards/css/pre.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/css/pre'>;
}
declare module '@userstory/stylelint-config/standards/css/userstory-cp.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/css/userstory-cp'>;
}
declare module '@userstory/stylelint-config/standards/css/userstory-csg.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/css/userstory-csg'>;
}
declare module '@userstory/stylelint-config/standards/css/userstory-kips.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/css/userstory-kips'>;
}
declare module '@userstory/stylelint-config/standards/css/userstory-touch-tv.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/css/userstory-touch-tv'>;
}
declare module '@userstory/stylelint-config/standards/less/manual.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/less/manual'>;
}
declare module '@userstory/stylelint-config/standards/less/post.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/less/post'>;
}
declare module '@userstory/stylelint-config/standards/less/pre.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/less/pre'>;
}
declare module '@userstory/stylelint-config/standards/less/userstory-cp.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/less/userstory-cp'>;
}
declare module '@userstory/stylelint-config/standards/less/userstory-csg.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/less/userstory-csg'>;
}
declare module '@userstory/stylelint-config/standards/less/userstory-kips.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/less/userstory-kips'>;
}
declare module '@userstory/stylelint-config/standards/less/userstory-touch-tv.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/less/userstory-touch-tv'>;
}
declare module '@userstory/stylelint-config/standards/post.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/post'>;
}
declare module '@userstory/stylelint-config/standards/pre.js' {
    declare module.exports: $Exports<'@userstory/stylelint-config/standards/pre'>;
}
