// flow-typed signature: ae6fa41f7067b5808de1e4422a37cfe4
// flow-typed version: <<STUB>>/@userstory/webpack-config_v^0.2.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@userstory/webpack-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@userstory/webpack-config' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@userstory/webpack-config/src/configs/assets' {
    declare module.exports: any;
}

declare module '@userstory/webpack-config/src/configs/base' {
    declare module.exports: any;
}

declare module '@userstory/webpack-config/src/configs/html' {
    declare module.exports: any;
}

declare module '@userstory/webpack-config/src/configs/style' {
    declare module.exports: any;
}

declare module '@userstory/webpack-config/src/configs/svg' {
    declare module.exports: any;
}

declare module '@userstory/webpack-config/src/index' {
    declare module.exports: any;
}

declare module '@userstory/webpack-config/src/utils/create-config' {
    declare module.exports: any;
}

// Filename aliases
declare module '@userstory/webpack-config/src/configs/assets.js' {
    declare module.exports: $Exports<'@userstory/webpack-config/src/configs/assets'>;
}
declare module '@userstory/webpack-config/src/configs/base.js' {
    declare module.exports: $Exports<'@userstory/webpack-config/src/configs/base'>;
}
declare module '@userstory/webpack-config/src/configs/html.js' {
    declare module.exports: $Exports<'@userstory/webpack-config/src/configs/html'>;
}
declare module '@userstory/webpack-config/src/configs/style.js' {
    declare module.exports: $Exports<'@userstory/webpack-config/src/configs/style'>;
}
declare module '@userstory/webpack-config/src/configs/svg.js' {
    declare module.exports: $Exports<'@userstory/webpack-config/src/configs/svg'>;
}
declare module '@userstory/webpack-config/src/index.js' {
    declare module.exports: $Exports<'@userstory/webpack-config/src/index'>;
}
declare module '@userstory/webpack-config/src/utils/create-config.js' {
    declare module.exports: $Exports<'@userstory/webpack-config/src/utils/create-config'>;
}
