export const INVOICE_MODULE_NAME = 'invoices';

export const INVOICE_ACTION_TYPE = {
    CREATE_INVOICE_FAIL: 'CREATE_INVOICE_FAIL',
    CREATE_INVOICE_START: 'CREATE_INVOICE_START',
    CREATE_INVOICE_SUCCESS: 'CREATE_INVOICE_SUCCESS',
    //////
    DELETE_INVOICE_FAIL: 'DELETE_INVOICE_FAIL',
    DELETE_INVOICE_START: 'DELETE_INVOICE_START',
    DELETE_INVOICE_SUCCESS: 'DELETE_INVOICE_SUCCESS',
    //////
    GET_INVOICE_FAIL: 'GET_INVOICE_FAIL',
    GET_INVOICE_START: 'GET_INVOICE_START',
    GET_INVOICE_SUCCESS: 'GET_INVOICE_SUCCESS',
    /////
    UPDATE_INVOICE_FAIL: 'UPDATE_INVOICE_FAIL',
    UPDATE_INVOICE_START: 'UPDATE_INVOICE_START',
    UPDATE_INVOICE_SUCCESS: 'UPDATE_INVOICE_SUCCESS',
};
